# Generated by Django 5.0.4 on 2024-05-06 02:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('Auteur', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('Langue', models.CharField(choices=[('', 'Select langue'), ('AR', 'Arabe'), ('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('AUTRE', 'Autre')], max_length=6)),
                ('Quantite_achete', models.PositiveBigIntegerField(default=0)),
                ('Quantite_Disponible', models.PositiveIntegerField(default=0)),
                ('Statut', models.CharField(choices=[('Disponible pour prêt', 'Disponible'), ('Hors prêt', 'Hors prêt')], default='Disponible pour prêt', max_length=50)),
                ('Cover', models.ImageField(upload_to='Bouquin/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Date_de_naissance', models.DateField()),
                ('CNI', models.CharField(max_length=20)),
                ('Date_d_inscription', models.DateField(auto_now_add=True)),
                ('Statut', models.CharField(default='Active', max_length=50)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_exemplaire', models.CharField(max_length=100)),
                ('Statut', models.CharField(default='Disponible', max_length=50)),
                ('Bouqin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.bouquin')),
            ],
        ),
        migrations.CreateModel(
            name='bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Identifient', models.CharField(editable=False, max_length=20, unique=True)),
                ('Nom', models.CharField(blank=True, max_length=50, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_emprunt', models.DateField(auto_now_add=True)),
                ('Date_retour', models.DateField()),
                ('Date_retourne', models.DateField(blank=True, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.client')),
                ('Exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.exemplaire')),
                ('bibliothecaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
