# Generated by Django 5.0.4 on 2024-05-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliothecaire',
            options={},
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='user_permissions',
        ),
    ]
