# Generated by Django 5.0.4 on 2024-05-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0002_alter_bibliothecaire_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplaire',
            old_name='Bouqin',
            new_name='Bouquin',
        ),
    ]
