# Generated by Django 5.0.4 on 2024-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0003_rename_bouqin_exemplaire_bouquin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='Date_retourne',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='Retourne',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
