# Generated by Django 5.0.4 on 2024-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0004_remove_emprunt_date_retourne_emprunt_retourne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquin',
            name='Cover',
            field=models.ImageField(default='/imgs/cover.jpg', upload_to='Bouquin/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='/imgs/client.png', upload_to='clients/'),
        ),
    ]
