# Generated by Django 5.0.4 on 2024-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0005_alter_bouquin_cover_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquin',
            name='Cover',
            field=models.ImageField(default='/cover.jpg', upload_to='Bouquin/'),
        ),
        migrations.AlterField(
            model_name='bouquin',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bouquin',
            name='ISBN',
            field=models.CharField(help_text='must be unique', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='/client.png', upload_to='clients/'),
        ),
    ]
