# Generated by Django 5.0.4 on 2024-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0006_alter_bouquin_cover_alter_bouquin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CNI',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
