# Generated by Django 5.0.4 on 2024-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0008_alter_bouquin_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquin',
            name='ISBN',
            field=models.CharField(help_text='must be unique', max_length=13, unique=True),
        ),
    ]
