# Generated by Django 5.0.4 on 2024-05-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0010_alter_emprunt_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.client'),
        ),
    ]
